name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.4

      - name: Install dependencies
        run: go get -v -t -d ./...

      - name: Run tests
        run: go test -v ./...
